server:
  port: 8081

spring:
  application:
    name: GraphQL-Demo
  datasource:
    url: jdbc:postgresql://localhost:5432/graphql
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update